= ["Connectors reference"]
:last_updated: 11/11/2019
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar
:summary: Learn about the external database connectors necessary for ThoughtSpot Embrace.

Here is a list of all of the external database connectors, and their connection credentials, that you must save in ThoughtSpot Embrace.
As you create a new external connection, you need specific connection information to establish seamless and secure connection with that database.

== Snowflake

* *Connection name*: Mandatory.
Enter a new Snowflake connection name.
* *Description*: Optional.
Provide a short description about the connection.
* *Account Name*: Mandatory.
Enter the account name associated with the Snowflake connection.
* *User*: Mandatory.
Enter the Snowflake account username.
* *Password*: Mandatory.
Enter the Snowflake account password.
* *Role*: Mandatory.
Specify the privilege of the user.
* *Warehouse*: Mandatory.
Specify the warehouse associated with the connection.
* *Database*: Optional.
Specify the database associated with the account.
* *Schema*: Optional.
Specify the schema associated with the database.

== Related articles

* link:{{ site.baseurl }}/data-integrate/embrace/getting-started/setup-a-new-connection.html[Add a connection]
* link:{{ site.baseurl }}/data-integrate/embrace/getting-started/modify-a-connection.html[Modify a connection]
