= ["Parameters of the cluster create command"]
:last_updated: ["12/19/2019"]
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar
:summary: Learn the parameters of the cluster create command.

[#using-cluster-create]
== Using the cluster create command

To install your appliance, you must install the cluster.

. *Copy the release tarball* In your Terminal (Apple) or using https://winscp.net/eng/index.php[Winscp] (Windows application), copy the downloaded release tarball to /home/admin/ and run the cluster installer as shown below.
+ Run the secure copy command: `scp <release-number> admin@<hostname>:/home/admin/<file-name>`.
Note the following parameters: +
 ** `release-number` is the version of ThoughtSpot you have on your cluster, such as `6.0` or `5.3`.
`release-number` is of the form `0.0.tar.gz`.
 ** `hostname` is your network hostname.
Ask your network administrator if you do not know your hostname.
 ** `file-name` is the name of the tarball file on your local machine.
For example:
+
----
 $ scp 6.0.tar.gz admin@ThoughtSpot:/home/admin/TS-tarball.
----
+
ThoughtSpot recommends that you start the session using https://linux.die.net/man/1/screen[screen], so you do not lose your progress if you lose your connection at any point.
+
----
 $ scp <release-number> admin@<hostname>:/home/admin/<file-name>
----
. *Run the `cluster create` command* Run `tscli cluster create <release-number>` in your terminal.
+ If you are using an s3 or GCS bucket for object storage, include the flag `--enable_cloud_storage=s3` or `--enable_cloud_storage=gcs`.
GCS is GCP's object storage, and s3 is AWS's object storage.
+
----
 $ tscli cluster create 6.0.tar.gz --enable_cloud_storage=s3
----
+
----
 $ tscli cluster create 6.0.tar.gz --enable_cloud_storage=gcs
----

. *Fill out your specific information* Fill out the cluster name, cluster ID, email alert preferences and the IP's of the nodes at the prompts specified in link:{{ site.baseurl }}/appliance/hardware/parameters-cluster-create.html#parameters-cluster-create[Parameters of ThoughtSpot Installer] below.

Refer to link:{{ site.baseurl }}/appliance/hardware/parameters-cluster-create.html#parameters-cluster-create[Parameters of ThoughtSpot Installer] for further information.
Refer to link:{{ site.baseurl }}/appliance/hardware/cluster-create.html[Using the cluster create command] to see the expected output of the install command, `tscli cluster create`.

Do not edit any part of the installer file except the sections specified in link:{{ site.baseurl }}/appliance/hardware/parameters-cluster-create.html#parameters-cluster-create[Parameters of ThoughtSpot Installer].
If you delete colons, commas, or other parts of the code, setup may fail.

[#parameters-cluster-create]
=== Parameters of ThoughtSpot Installer

*Cluster Name* Name your cluster, using only letters and numbers.
Instead of spaces, use dashes.
For example, thoughtspot-cluster.

*Cluster ID* Enter the ID of your cluster, in the form yymmX0000, where yymm refers to the year and month you are setting up the cluster, X serves as a separator, and 0000 is the number of your cluster, as in 0001 and 0002.
For example, 1909X0001.

*Host IPs*	Enter the IP addresses of all cluster hosts, in the form 000.000.000.000.
For example, 192.168.7.70.
Use spaces instead of commas to separate multiple IP addresses.

*Email alerts*	Enter the email addresses you would like to receive alerts about this cluster, in the form company@example.com.
The address prod-alerts@thoughtspot.com appears automatically and should remain, so that ThoughtSpot can be aware of the status of your cluster.
Separate email addresses using a space.

== Related information

* link:{{ site.baseurl }}/appliance/hardware/installing-the-smc.html[Deploying on the SMC appliance]
* link:{{ site.baseurl }}/appliance/aws/installing-aws.html[Configure ThoughtSpot nodes in AWS]
* link:{{ site.baseurl }}/appliance/gcp/installing-gcp.html[Configure ThoughtSpot nodes in GCP]
* link:{{ site.baseurl }}/appliance/vmware/installing-vmware.html[Configure ThoughtSpot nodes in VMware]
* link:{{ site.baseurl }}/appliance/azure/installing-azure.html[Configure ThoughtSpot nodes in Azure]
* link:{{ site.baseurl }}/appliance/hardware/installing-dell.html[Deploying on the Dell Appliance]
* link:{{ site.baseurl }}/appliance/hardware/cluster-create.html[Using the cluster create command]
