= ["About disaster recovery"]
:last_updated: tbd
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar
:toc: false

Disaster recovery is the ability to recover from a hardware or software failure or a catastrophic event.
ThoughtSpot protects you from data loss in the event of a hardware or software failure or a catastrophic event.

ThoughtSpot takes snapshots of itself automatically at periodic intervals.
These can be pulled out as backups at intervals or manually as needed.
See the ThoughtSpot Administrator Guide for details on backups, snapshots and restore operations.

The information here addresses disaster recovery specifically.
These are some potential types of failure, listed in increasing order of severity:

* *link:{{ site.baseurl }}/disaster-recovery/disk-failure.html[Disk failure]* + ThoughtSpot uses replication of stored data.
When a disk goes bad, ThoughtSpot continues to operate.
* *link:{{ site.baseurl }}/disaster-recovery/node-failure.html[Node failure]* + ThoughtSpot uses replication of stored data.
When a disk goes bad, ThoughtSpot continues to operate.
* *link:{{ site.baseurl }}/disaster-recovery/cluster-replacement.html[Cluster replacement]* + Cluster replacement can be achieved using a mirrored system architecture.
This allows you to recover an entire system very quickly without data loss.

ThoughtSpot supports recovery from disk or node failure within each appliance.
You can also architect your system to support loss of an entire appliance, which is the highest level of disaster recovery.
