'''

title: [GCP configuration options]

last_updated: tbd sidebar: mydoc_sidebar permalink: /:collection/:path.html -- ThoughtSpot can be deployed in your GCP environment by deploying compute (VM) instances in your VPC as well as an underlying persistent storage infrastructure.
Currently two configuration modes are supported by ThoughtSpot:

* Mode 1: Compute VMs + SSD Persistent Disk storage-only
* Mode 2: Compute VMs + SSD Persistent Disk and Google Cloud Storage (GCS).

For more information about Persistant Storage, see https://cloud.google.com/compute/docs/disks/#pdspecs[Zonal Persistent SSD disks] in Google's Cloud documentation.

For more information about Google Cloud Storage, see https://cloud.google.com/compute/docs/disks/#gcsbuckets[Cloud Storage Buckets] in Google's Cloud documentation.

All GCP VMs (nodes) in a ThoughtSpot cluster must be in the same zone (and, therefore, also in the same region).
ThoughtSpot does not support deploying VMs (nodes) of the same cluster across zones.
For more information, see https://cloud.google.com/compute/docs/regions-zones/[Regions and Zones] in Google's Cloud documentation.

== ThoughtSpot GCP instance types

=== VMs with Persistent Disk-only storage

image::{{ site.baseurl }}/images/persistent-storage-ssd.svg[]

|===
| Per VM user data capacity | Instance type | CPU/RAM | Recommended per-VM + Zonal Persistent SSD Disk volume

| 208 GB
| n1-highmem-64
| 64/416
| 2x 1 TB

| 312 GB
| n1-highmem-96
| 96/624
| 2x 1.5 TB

| 100 GB
| n1-highmem-32
| 32/208
| 2X 400 GB

| 20 GB
| n1-highmem-16
| 16/122
| 2X 400 GB

| 180 GB
| n1-standard-96
| 96/330
| 2X 1 TB
|===

=== VMs with Persistent Disk and Google Cloud storage

image::{{ site.baseurl }}/images/persistent-storage-ssd-gcs.svg[]

|===
| Per VM user data capacity | Instance type | CPU/RAM | Recommended per-VM + Zonal Persistent SSD Disk volume

| 208 GB
| n1-highmem-64
| 64/416
| 1X 500 GB

| 312 GB
| n1-highmem-96
| 96/624
| 1X 500 GB

| 100 GB
| n1-highmem-32
| 32/208
| 1X 500 GB

| 20 GB
| n1-highmem-16
| 16/122
| 1X 500 GB

| 180 GB
| n1-standard-96
| 96/330
| 1X 500 GB
|===
