= ["Configure ThoughtSpot nodes in Azure"]
:last_updated: ["12/12/2019"]
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar
:summary: Prepare to install your ThoughtSpot cluster by configuring nodes.

Before you can install a ThoughtSpot cluster in Azure, you must configure your nodes.

[#installation-prerequisites]
== Installation Prerequisites

Ensure the successful creation of the virtual machines (VMs) before you install the ThoughtSpot cluster in Azure.

. *Review configuration options* Refer to link:{{ site.baseurl }}/appliance/azure/configuration-options.html[Azure configuration options] for detailed instance specs.
. *Create the instance* Refer to link:{{ site.baseurl }}/appliance/azure/launch-an-instance.html[Set up Azure for ThoughtSpot] to create and launch your instance.
. *Review required ports* Refer to link:{{ site.baseurl }}/appliance/firewall-ports.html[Network Policies] to view the required ports for successful operation of ThoughtSpot.

[#configure-nodes]
== Configure Nodes

After creating the instance, you must configure the nodes.
Follow the steps in this checklist.

[cols=2*]
|===
| &#10063;
| link:installing-azure#node-step-1[Step 1: Log into your cluster]

| &#10063;
| link:installing-azure#node-step-2[Step 2: Get a template for network configuration]

| &#10063;
| link:installing-azure#node-step-3[Step 3: Prepare node configuration]

| &#10063;
| link:installing-azure#node-step-4[Step 4: Configure the nodes]

| &#10063;
| link:installing-azure#node-step-5[Step 5: Confirm node configuration]
|===

[#node-step-1]
=== Step 1: Log into your cluster

Use Terminal on a Mac or a terminal emulator on Windows to log into your cluster.
Log in using the ssh private key provided by ThoughtSpot.
+ If you do not have a private key, contact link:{{ site.baseurl }}/appliance/contact.html[ThoughtSpot Support] by email or through the support portal.

To log into your cluster, run `ssh -i <private-key> admin@<public-vm-ip>`.

----
    $ ssh -i <private_key> admin@<public-vm-ip>
----

[#node-step-2]
=== Step 2: Get a template for network configuration

Run the `tscli cluster get-config` command to get a template for network configuration for the new cluster.
Redirect it to the file `nodes.config`.
+ You can find more information on this process in the link:{{ site.baseurl }}/appliance/hardware/nodesconfig-example.html[`nodes.config` file reference].

 $ tscli cluster get-config |& tee nodes.config

[#node-step-3]
=== Step 3: Prepare node configuration

. Add your specific network information for the nodes in the `nodes.config` file, as demonstrated in the link:{{ site.baseurl }}/appliance/hardware/nodesconfig-example.html#autodiscovery-of-one-node-example[autodiscovery of one node example].
. Fill in the areas specified in link:{{ site.baseurl }}/appliance/hardware/parameters-nodesconfig.html[Parameters of the nodes.config file] with your specific network information.
+ If you have additional nodes, complete each node within the nodes.config file in the same way.

Do not edit any part of the `nodes.config` file except the sections described in link:{{ site.baseurl }}/appliance/hardware/parameters-nodesconfig.html[Parameters of the nodes.config file].
If you delete quotation marks, commas, or other parts of the code, it may cause setup to fail.

[#node-step-4]
=== Step 4: Configure the nodes

Configure the nodes in the `nodes.config` file using the `set-config` command.

. Disable the `firewalld` service by running `sudo systemctl stop firewalld` in your terminal.
The `firewalld` service is a Linux firewall that must be off for ThoughtSpot installation.
After the cluster installer reboots the nodes, `firewalld` automatically turns back on.
+
----
 $ sudo systemctl stop firewalld
----

. To make sure you temporarily disabled `firewalld`, run `sudo systemctl status firewalld`.
Your output should specify that `firewalld` is inactive.
It may look something like the following:
+
----
 $ sudo systemctl status firewalld
   ● firewalld.service - firewalld - dynamic firewall daemon
     Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
----

. Run the configuration command: `$ cat nodes.config | tscli cluster set-config`.
+ If the command returns an error, refer to link:{{ site.baseurl }}#set-config-error-recovery[set-config error recovery].
+ After you run the node configuration command, your output appears similar to the following:
+
----
 $ cat nodes.config | tscli cluster set-config

 Connecting to local node-scout
 Setting up hostnames for all nodes
 Setting up networking interfaces on all nodes
 Setting up hosts file on all nodes
 Setting up IPMI configuration
 Setting up NTP Servers
 Setting up Timezone
 Done setting up ThoughtSpot
----

[#node-step-5]
=== Step 5: Confirm node configuration

Use the `get-config` command to confirm node configuration.
+ Your output may look similar to the following:

[source,console]
----
$ tscli cluster get-config

{
  "ClusterId": "",
  "ClusterName": "",
  "DataNetmask": "255.255.252.0",
  "DataGateway": "192.168.4.1",
  "IPMINetmask": "255.255.252.0",
  "IPMIGateway": "192.168.4.1",
  "Timezone": "America/Los_Angeles",
  "NTPServers": "0.centos.pool.ntp.org,1.centos.pool.ntp.org,2.centos.pool.ntp.org,3.centos.pool.ntp.org",
  "DNS": "192.168.2.200,8.8.8.8",
  "SearchDomains": "example.company.com",
  "Nodes": {
	"ac:1f:6b:8a:77:f6": {
  	"NodeId": "ac:1f:6b:8a:77:f6",
  	"Hostname": "Thoughtspot-server1",
  	"DataIface": {
    	"Name": "eth2",
    	"IPv4": "192.168.7.70"
  	},
  	"IPMI": {
    	"IPv4": "192.168.5.70"
  	}
	}
  }
}
----

== Install ThoughtSpot software

Next, link:{{ site.baseurl }}/appliance/azure/azure-cluster-install.html[install your ThoughtSpot clusters].

{% include content/install/install-cluster-error-recovery.md %}

== Related information

Use these references for successful installation and administration of ThoughtSpot.

* link:{{ site.baseurl }}/appliance/hardware/nodesconfig-example[the nodes.config file]
* link:{{ site.baseurl }}/appliance/hardware/parameters-nodesconfig.html[Parameters of the nodes.config file]
* link:{{ site.baseurl }}/appliance/hardware/cluster-create.html[Using the cluster create command]
* link:{{ site.baseurl }}/appliance/hardware/parameters-cluster-create.html[Parameters of the `cluster create` command]
* https://docs.thoughtspot.com[ThoughtSpot Documentation]
* link:{{ site.baseurl }}/appliance/contact.html[Contact Support]
