= ["View an answer from an expert"]
:last_updated: 09/23/2019
:permalink: /:collection/:path.html
:sidebar: mydoc_sidebar
:summary: How to find an answer from an expert

When you use *Ask an expert* to get help, you can view the answer after the expert responds.

To view the answer:

Click the link in the email you receive automatically when the expert answers your question, or if you're not set up with an email in ThoughtSpot:

. Click *Answers* in the top menu.
. Click the name of the answer you want to review.
If you can't find it, try using the *Yours* filter to narrow down the list.
. View your answer.

The answer will include any changes the expert made, to get to the answer you were looking for.
You should review the new answer, to learn from the things the expert did to answer your question.

Note that the answer is a full fledged ThoughtSpot answer.
This means that you can pin it to a pinboard, edit it, or share it with others, just like the result of any ThoughtSpot search.

== Related information

* link:{{ site.baseurl }}/end-user/search/ask-an-expert.html[Ask an expert]
* link:{{ site.baseurl }}/end-user/search/answer-expert-question.html[Answer Ask an expert questions]
