'''

title: ["Manage experts or add an expert"]

last_updated: 09/23/2019 summary: "You can designate experts for each data source, so users won't get stuck if they need help." sidebar: mydoc_sidebar toc: true permalink: /:collection/:path.html --

If your users occasionally struggle to answer a specific question, build a chart you have in mind, or find something in your data, you can enable *Ask an expert*.
This lets them request help from someone in your organization.

The request goes to the person in your company who knows the data source very well, and how to search it in ThoughtSpot.
When the request is answered, the user will be able to see the result in the *Answers* listing in ThoughtSpot.

You can see how an end user experiences *Ask an expert* link:{{ site.baseurl }}/end-user/search/ask-an-expert.html[here].

== Add an expert to a data source

Adding an expert is what enables *Ask an expert* to work in your ThoughtSpot instance.
Until you do these steps, users won't see the prompt to *Ask an expert* when using that data source.

To add an expert to a data source:

. Let the expert(s) know to expect user questions to start coming their way in email.
If your expert(s) don't have an email in ThoughtSpot, they must link:{{ site.baseurl }}/end-user/search/answer-expert-question.html[check in ThoughtSpot for requested answers].
. Click the name of the worksheet or table from the *Data* page.
. Click the three dot icon in the upper right side of the page and select *Manage experts*.
. Make your selections and click *Save*.

== Related information

* link:semantic-modeling.html#[Model the data for searching]
* link:{{ site.baseurl }}/end-user/search/ask-an-expert.html[Ask an Expert]
